name = "invitation-weeding-ff-new-0-1"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
name = "invitation-weeding-ff-new-0-1"

[[env.production.routes]]
pattern = "felbifernandya.pages.dev"
zone_name = "pages.dev"